from alembic import op
import sqlalchemy as sa
revision='0018_product_compliance'; down_revision='0017_trade_rules'; branch_labels=None; depends_on=None
def upgrade():
    op.create_table('product_compliance',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('product_id',sa.Integer(),sa.ForeignKey('products.id'),nullable=False),sa.Column('market_id',sa.Integer(),sa.ForeignKey('markets.id'),nullable=False),sa.Column('hs_code',sa.String(30),nullable=False),sa.Column('hs_description',sa.String(500)),sa.Column('classification_basis',sa.Text()),sa.Column('status',sa.String(30),nullable=False,server_default='Unverified'),sa.Column('confidence',sa.Float(),nullable=False,server_default='0'),sa.Column('source_url',sa.Text()),sa.Column('source_title',sa.String(300)),sa.Column('retrieved_at',sa.DateTime(timezone=True),nullable=False),sa.Column('notes',sa.Text()),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False))
    for n,c in [('ix_product_compliance_product_id',['product_id']),('ix_product_compliance_market_id',['market_id']),('ix_product_compliance_hs_code',['hs_code']),('ix_product_compliance_status',['status'])]: op.create_index(n,'product_compliance',c)
    op.create_index('ix_product_compliance_product_market','product_compliance',['product_id','market_id'])
    op.create_table('compliance_requirements',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('product_compliance_id',sa.Integer(),sa.ForeignKey('product_compliance.id'),nullable=False),sa.Column('trade_rule_id',sa.Integer(),sa.ForeignKey('trade_rules.id')),sa.Column('requirement_type',sa.String(50),nullable=False),sa.Column('title',sa.String(300),nullable=False),sa.Column('mandatory',sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column('status',sa.String(30),nullable=False,server_default='Unverified'),sa.Column('documents',sa.JSON(),nullable=False,server_default='[]'),sa.Column('evidence',sa.JSON(),nullable=False,server_default='{}'),sa.Column('source_url',sa.Text()),sa.Column('source_title',sa.String(300)),sa.Column('notes',sa.Text()),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False))
    for n,c in [('ix_compliance_requirements_product_compliance_id',['product_compliance_id']),('ix_compliance_requirements_trade_rule_id',['trade_rule_id']),('ix_compliance_requirements_requirement_type',['requirement_type']),('ix_compliance_requirements_mandatory',['mandatory']),('ix_compliance_requirements_status',['status'])]: op.create_index(n,'compliance_requirements',c)
def downgrade():
    for n in ['ix_compliance_requirements_status','ix_compliance_requirements_mandatory','ix_compliance_requirements_requirement_type','ix_compliance_requirements_trade_rule_id','ix_compliance_requirements_product_compliance_id']: op.drop_index(n,table_name='compliance_requirements')
    op.drop_table('compliance_requirements')
    op.drop_index('ix_product_compliance_product_market',table_name='product_compliance')
    for n in ['ix_product_compliance_status','ix_product_compliance_hs_code','ix_product_compliance_market_id','ix_product_compliance_product_id']: op.drop_index(n,table_name='product_compliance')
    op.drop_table('product_compliance')
