"""trade route and border cost intelligence
Revision ID: 0021_trade_route_intelligence
Revises: 0020_landed_cost_intelligence
"""
from alembic import op
import sqlalchemy as sa
revision='0021_trade_route_intelligence'; down_revision='0020_landed_cost_intelligence'; branch_labels=None; depends_on=None

def upgrade():
    op.create_table('trade_route_profiles',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('opportunity_id',sa.Integer(),sa.ForeignKey('opportunities.id'),nullable=True),sa.Column('market_id',sa.Integer(),sa.ForeignKey('markets.id'),nullable=True),sa.Column('name',sa.String(200),nullable=False),sa.Column('origin',sa.String(250),nullable=False),sa.Column('destination',sa.String(250),nullable=False),sa.Column('currency',sa.String(10),nullable=False),sa.Column('verification_status',sa.String(30),nullable=False),sa.Column('source_url',sa.Text(),nullable=True),sa.Column('source_title',sa.String(300),nullable=True),sa.Column('assumptions',sa.JSON(),nullable=False),sa.Column('is_active',sa.Boolean(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False))
    op.create_index('ix_trade_route_profiles_opportunity_id','trade_route_profiles',['opportunity_id']); op.create_index('ix_trade_route_profiles_market_id','trade_route_profiles',['market_id']); op.create_index('ix_trade_route_profiles_verification_status','trade_route_profiles',['verification_status'])
    op.create_table('trade_route_segments',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('route_id',sa.Integer(),sa.ForeignKey('trade_route_profiles.id'),nullable=False),sa.Column('sequence',sa.Integer(),nullable=False),sa.Column('segment_type',sa.String(30),nullable=False),sa.Column('from_location',sa.String(250),nullable=False),sa.Column('to_location',sa.String(250),nullable=False),sa.Column('transport_mode',sa.String(40),nullable=False),sa.Column('border_or_port',sa.String(160),nullable=True),sa.Column('distance_km',sa.Float(),nullable=True),sa.Column('transit_days',sa.Float(),nullable=True),sa.Column('freight_cost',sa.Float(),nullable=False),sa.Column('border_cost',sa.Float(),nullable=False),sa.Column('transit_cost',sa.Float(),nullable=False),sa.Column('destination_handling',sa.Float(),nullable=False),sa.Column('other_cost',sa.Float(),nullable=False),sa.Column('currency',sa.String(10),nullable=False),sa.Column('verification_status',sa.String(30),nullable=False),sa.Column('source_url',sa.Text(),nullable=True),sa.Column('assumptions',sa.JSON(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False))
    op.create_index('ix_trade_route_segments_route_id','trade_route_segments',['route_id']); op.create_index('ix_trade_route_segments_sequence','trade_route_segments',['sequence']); op.create_index('ix_trade_route_segments_verification_status','trade_route_segments',['verification_status'])
    op.create_table('trade_route_calculations',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('route_id',sa.Integer(),sa.ForeignKey('trade_route_profiles.id'),nullable=False),sa.Column('opportunity_id',sa.Integer(),sa.ForeignKey('opportunities.id'),nullable=True),sa.Column('quantity',sa.Float(),nullable=False),sa.Column('currency',sa.String(10),nullable=False),sa.Column('freight_total',sa.Float(),nullable=False),sa.Column('border_total',sa.Float(),nullable=False),sa.Column('transit_total',sa.Float(),nullable=False),sa.Column('destination_handling',sa.Float(),nullable=False),sa.Column('other_cost',sa.Float(),nullable=False),sa.Column('total_route_cost',sa.Float(),nullable=False),sa.Column('route_unit_cost',sa.Float(),nullable=False),sa.Column('distance_km',sa.Float(),nullable=False),sa.Column('transit_days',sa.Float(),nullable=False),sa.Column('status',sa.String(30),nullable=False),sa.Column('assumptions',sa.JSON(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False))
    op.create_index('ix_trade_route_calculations_route_id','trade_route_calculations',['route_id']); op.create_index('ix_trade_route_calculations_opportunity_id','trade_route_calculations',['opportunity_id'])

def downgrade():
    op.drop_table('trade_route_calculations'); op.drop_table('trade_route_segments'); op.drop_table('trade_route_profiles')
