from datetime import datetime, timezone
from sqlalchemy import String, Text, Float, Integer, Boolean, DateTime, ForeignKey, JSON, Index
from sqlalchemy.orm import Mapped, mapped_column, relationship
from ..database import Base

def now(): return datetime.now(timezone.utc)

class TimestampMixin:
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=now, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=now, onupdate=now, nullable=False)

class Admin(TimestampMixin, Base):
    __tablename__='admins'
    id: Mapped[int]=mapped_column(primary_key=True)
    username: Mapped[str]=mapped_column(String(80), unique=True, index=True)
    password_hash: Mapped[str]=mapped_column(String(255))
    is_active: Mapped[bool]=mapped_column(Boolean, default=True)
    role: Mapped[str]=mapped_column(String(40), default='Admin', index=True)

class SessionToken(TimestampMixin, Base):
    __tablename__='session_tokens'
    id: Mapped[int]=mapped_column(primary_key=True)
    admin_id: Mapped[int]=mapped_column(ForeignKey('admins.id'), index=True)
    token_hash: Mapped[str]=mapped_column(String(64), unique=True, index=True)
    expires_at: Mapped[datetime]=mapped_column(DateTime(timezone=True), index=True)
    revoked_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True), nullable=True)

class Product(TimestampMixin, Base):
    __tablename__='products'
    id: Mapped[int]=mapped_column(primary_key=True)
    name: Mapped[str]=mapped_column(String(200), index=True)
    normalized_name: Mapped[str]=mapped_column(String(200), index=True)
    category: Mapped[str|None]=mapped_column(String(120), nullable=True, index=True)
    sub_category: Mapped[str|None]=mapped_column(String(120), nullable=True)
    unit: Mapped[str|None]=mapped_column(String(30), nullable=True)
    aliases: Mapped[list]=mapped_column(JSON, default=list)
    specifications: Mapped[dict]=mapped_column(JSON, default=dict)

class Market(TimestampMixin, Base):
    __tablename__='markets'
    id: Mapped[int]=mapped_column(primary_key=True)
    source_country: Mapped[str]=mapped_column(String(100), index=True)
    target_country: Mapped[str]=mapped_column(String(100), index=True)
    name: Mapped[str]=mapped_column(String(200), index=True)
    active: Mapped[bool]=mapped_column(Boolean, default=True)
    default_currency: Mapped[str]=mapped_column(String(10), default='USD')
    languages: Mapped[list]=mapped_column(JSON, default=list)
    incoterms: Mapped[list]=mapped_column(JSON, default=list)
    transport_modes: Mapped[list]=mapped_column(JSON, default=list)
    scoring_weights: Mapped[dict]=mapped_column(JSON, default=dict)
    commercial_rules: Mapped[dict]=mapped_column(JSON, default=dict)

class CountryProfile(TimestampMixin, Base):
    __tablename__='country_profiles'
    id: Mapped[int]=mapped_column(primary_key=True)
    country_code: Mapped[str]=mapped_column(String(10), unique=True, index=True)
    country_name: Mapped[str]=mapped_column(String(120), index=True)
    currencies: Mapped[list]=mapped_column(JSON, default=list)
    languages: Mapped[list]=mapped_column(JSON, default=list)
    payment_methods: Mapped[list]=mapped_column(JSON, default=list)
    customs_notes: Mapped[dict]=mapped_column(JSON, default=dict)
    logistics_nodes: Mapped[list]=mapped_column(JSON, default=list)
    source_url: Mapped[str|None]=mapped_column(Text, nullable=True)
    source_title: Mapped[str|None]=mapped_column(String(300), nullable=True)
    retrieved_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True), nullable=True)
    verification_status: Mapped[str]=mapped_column(String(30), default='Unverified', index=True)

class TradeRule(TimestampMixin, Base):
    __tablename__='trade_rules'
    id: Mapped[int]=mapped_column(primary_key=True)
    market_id: Mapped[int]=mapped_column(ForeignKey('markets.id'), index=True)
    country_profile_id: Mapped[int|None]=mapped_column(ForeignKey('country_profiles.id'), nullable=True, index=True)
    rule_type: Mapped[str]=mapped_column(String(50), index=True)
    title: Mapped[str]=mapped_column(String(300))
    hs_code: Mapped[str|None]=mapped_column(String(30), nullable=True, index=True)
    product_scope: Mapped[str|None]=mapped_column(String(250), nullable=True, index=True)
    mandatory: Mapped[bool]=mapped_column(Boolean, default=True, index=True)
    status: Mapped[str]=mapped_column(String(30), default='Unverified', index=True)
    requirement: Mapped[str]=mapped_column(Text)
    documents: Mapped[list]=mapped_column(JSON, default=list)
    authority: Mapped[str|None]=mapped_column(String(250), nullable=True)
    source_url: Mapped[str|None]=mapped_column(Text, nullable=True)
    source_title: Mapped[str|None]=mapped_column(String(300), nullable=True)
    published_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True), nullable=True)
    effective_from: Mapped[datetime|None]=mapped_column(DateTime(timezone=True), nullable=True)
    effective_to: Mapped[datetime|None]=mapped_column(DateTime(timezone=True), nullable=True)
    retrieved_at: Mapped[datetime]=mapped_column(DateTime(timezone=True), default=now)
    notes: Mapped[str|None]=mapped_column(Text, nullable=True)
    __table_args__=(Index('ix_trade_rules_market_scope','market_id','product_scope'),)

class ProductCompliance(TimestampMixin, Base):
    __tablename__='product_compliance'
    id: Mapped[int]=mapped_column(primary_key=True)
    product_id: Mapped[int]=mapped_column(ForeignKey('products.id'), index=True)
    market_id: Mapped[int]=mapped_column(ForeignKey('markets.id'), index=True)
    hs_code: Mapped[str]=mapped_column(String(30), index=True)
    hs_description: Mapped[str|None]=mapped_column(String(500), nullable=True)
    classification_basis: Mapped[str|None]=mapped_column(Text, nullable=True)
    status: Mapped[str]=mapped_column(String(30), default='Unverified', index=True)
    confidence: Mapped[float]=mapped_column(Float, default=0.0)
    source_url: Mapped[str|None]=mapped_column(Text, nullable=True)
    source_title: Mapped[str|None]=mapped_column(String(300), nullable=True)
    retrieved_at: Mapped[datetime]=mapped_column(DateTime(timezone=True), default=now)
    notes: Mapped[str|None]=mapped_column(Text, nullable=True)
    __table_args__=(Index('ix_product_compliance_product_market','product_id','market_id'),)

class ImportCostRule(TimestampMixin, Base):
    __tablename__='import_cost_rules'
    id: Mapped[int]=mapped_column(primary_key=True)
    market_id: Mapped[int]=mapped_column(ForeignKey('markets.id'), index=True)
    hs_code: Mapped[str]=mapped_column(String(30), index=True)
    product_scope: Mapped[str|None]=mapped_column(String(250), nullable=True, index=True)
    duty_percent: Mapped[float]=mapped_column(Float, default=0.0)
    excise_percent: Mapped[float]=mapped_column(Float, default=0.0)
    vat_percent: Mapped[float]=mapped_column(Float, default=0.0)
    other_percent: Mapped[float]=mapped_column(Float, default=0.0)
    fixed_fee: Mapped[float]=mapped_column(Float, default=0.0)
    currency: Mapped[str]=mapped_column(String(10), default='USD')
    vat_base: Mapped[str]=mapped_column(String(40), default='customs_plus_duty')
    other_base: Mapped[str]=mapped_column(String(40), default='customs_value')
    status: Mapped[str]=mapped_column(String(30), default='Unverified', index=True)
    authority: Mapped[str|None]=mapped_column(String(250), nullable=True)
    source_url: Mapped[str|None]=mapped_column(Text, nullable=True)
    source_title: Mapped[str|None]=mapped_column(String(300), nullable=True)
    published_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True), nullable=True)
    effective_from: Mapped[datetime|None]=mapped_column(DateTime(timezone=True), nullable=True)
    effective_to: Mapped[datetime|None]=mapped_column(DateTime(timezone=True), nullable=True)
    retrieved_at: Mapped[datetime]=mapped_column(DateTime(timezone=True), default=now)
    notes: Mapped[str|None]=mapped_column(Text, nullable=True)
    __table_args__=(Index('ix_import_cost_rules_market_hs','market_id','hs_code'),)

class ComplianceRequirement(TimestampMixin, Base):
    __tablename__='compliance_requirements'
    id: Mapped[int]=mapped_column(primary_key=True)
    product_compliance_id: Mapped[int]=mapped_column(ForeignKey('product_compliance.id'), index=True)
    trade_rule_id: Mapped[int|None]=mapped_column(ForeignKey('trade_rules.id'), nullable=True, index=True)
    requirement_type: Mapped[str]=mapped_column(String(50), index=True)
    title: Mapped[str]=mapped_column(String(300))
    mandatory: Mapped[bool]=mapped_column(Boolean, default=True, index=True)
    status: Mapped[str]=mapped_column(String(30), default='Unverified', index=True)
    documents: Mapped[list]=mapped_column(JSON, default=list)
    evidence: Mapped[dict]=mapped_column(JSON, default=dict)
    source_url: Mapped[str|None]=mapped_column(Text, nullable=True)
    source_title: Mapped[str|None]=mapped_column(String(300), nullable=True)
    notes: Mapped[str|None]=mapped_column(Text, nullable=True)

class Source(TimestampMixin, Base):
    __tablename__='sources'
    id: Mapped[int]=mapped_column(primary_key=True)
    source_type: Mapped[str]=mapped_column(String(80), index=True)
    name: Mapped[str]=mapped_column(String(200))
    base_url: Mapped[str|None]=mapped_column(Text, nullable=True)
    allowed: Mapped[bool]=mapped_column(Boolean, default=True)
    access_mode: Mapped[str]=mapped_column(String(40), default='manual', index=True)
    capability: Mapped[str]=mapped_column(String(80), default='manual_entry', index=True)
    configured: Mapped[bool]=mapped_column(Boolean, default=False, index=True)
    authenticated: Mapped[bool]=mapped_column(Boolean, default=False, index=True)
    availability_status: Mapped[str]=mapped_column(String(40), default='Unknown', index=True)
    last_checked_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True), nullable=True)
    last_success_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True), nullable=True)
    last_error: Mapped[str|None]=mapped_column(Text, nullable=True)
    limitations: Mapped[list]=mapped_column(JSON, default=list)
    discovery_status: Mapped[str|None]=mapped_column(String(40), nullable=True, index=True)
    discovery_score: Mapped[float|None]=mapped_column(Float, nullable=True, index=True)
    discovered_from_url: Mapped[str|None]=mapped_column(Text, nullable=True)
    discovery_evidence: Mapped[dict]=mapped_column(JSON, default=dict)
    freshness_status: Mapped[str]=mapped_column(String(30), default='Unknown', index=True)
    freshness_score: Mapped[float|None]=mapped_column(Float, nullable=True, index=True)
    observed_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True), nullable=True, index=True)
    published_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True), nullable=True, index=True)
    updated_at_source: Mapped[datetime|None]=mapped_column(DateTime(timezone=True), nullable=True, index=True)
    expires_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True), nullable=True, index=True)
    last_verified_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True), nullable=True, index=True)

class Supplier(TimestampMixin, Base):
    __tablename__='suppliers'
    id: Mapped[int]=mapped_column(primary_key=True)
    canonical_name: Mapped[str]=mapped_column(String(250), index=True)
    country: Mapped[str]=mapped_column(String(100), default='Iran', index=True)
    city: Mapped[str|None]=mapped_column(String(120), nullable=True, index=True)
    address: Mapped[str|None]=mapped_column(Text, nullable=True)
    phone: Mapped[str|None]=mapped_column(String(80), nullable=True)
    website: Mapped[str|None]=mapped_column(Text, nullable=True)
    verification_status: Mapped[str]=mapped_column(String(30), default='Unverified', index=True)
    confidence: Mapped[float]=mapped_column(Float, default=0.0)
    trust_score: Mapped[float]=mapped_column(Float, default=0.0, index=True)
    canonical_key: Mapped[str|None]=mapped_column(String(300), nullable=True, unique=True, index=True)
    is_archived: Mapped[bool]=mapped_column(Boolean, default=False, index=True)

class Buyer(TimestampMixin, Base):
    __tablename__='buyers'
    id: Mapped[int]=mapped_column(primary_key=True)
    canonical_name: Mapped[str]=mapped_column(String(250), index=True)
    country: Mapped[str]=mapped_column(String(100), index=True)
    city: Mapped[str|None]=mapped_column(String(120), nullable=True, index=True)
    address: Mapped[str|None]=mapped_column(Text, nullable=True)
    phone: Mapped[str|None]=mapped_column(String(80), nullable=True)
    website: Mapped[str|None]=mapped_column(Text, nullable=True)
    verification_status: Mapped[str]=mapped_column(String(30), default='Potential', index=True)
    confidence: Mapped[float]=mapped_column(Float, default=0.0)
    reliability_score: Mapped[float]=mapped_column(Float, default=0.0, index=True)
    canonical_key: Mapped[str|None]=mapped_column(String(300), nullable=True, unique=True, index=True)
    is_archived: Mapped[bool]=mapped_column(Boolean, default=False, index=True)

class Manufacturer(TimestampMixin, Base):
    __tablename__='manufacturers'
    id: Mapped[int]=mapped_column(primary_key=True)
    name: Mapped[str]=mapped_column(String(250), index=True)
    company: Mapped[str|None]=mapped_column(String(250), nullable=True)
    product_id: Mapped[int|None]=mapped_column(ForeignKey('products.id'), index=True)
    country: Mapped[str]=mapped_column(String(100), default='Iran', index=True)
    city: Mapped[str|None]=mapped_column(String(120), nullable=True, index=True)
    address: Mapped[str|None]=mapped_column(Text, nullable=True)
    latitude: Mapped[float|None]=mapped_column(Float, nullable=True)
    longitude: Mapped[float|None]=mapped_column(Float, nullable=True)
    capacity_value: Mapped[float|None]=mapped_column(Float, nullable=True)
    capacity_unit: Mapped[str|None]=mapped_column(String(30), nullable=True)
    phone: Mapped[str|None]=mapped_column(String(80), nullable=True)
    website: Mapped[str|None]=mapped_column(Text, nullable=True)
    source_id: Mapped[int|None]=mapped_column(ForeignKey('sources.id'), nullable=True, index=True)
    source_url: Mapped[str|None]=mapped_column(Text, nullable=True)
    source_title: Mapped[str|None]=mapped_column(String(300), nullable=True)
    retrieved_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True), nullable=True)
    verification_status: Mapped[str]=mapped_column(String(30), default='Unverified', index=True)
    confidence: Mapped[float]=mapped_column(Float, default=0.0)
    is_archived: Mapped[bool]=mapped_column(Boolean, default=False, index=True)

class Customer(TimestampMixin, Base):
    __tablename__='customers'
    id: Mapped[int]=mapped_column(primary_key=True)
    name: Mapped[str]=mapped_column(String(250), index=True)
    country: Mapped[str]=mapped_column(String(100), index=True)
    city: Mapped[str|None]=mapped_column(String(120), nullable=True, index=True)
    address: Mapped[str|None]=mapped_column(Text, nullable=True)
    latitude: Mapped[float|None]=mapped_column(Float, nullable=True)
    longitude: Mapped[float|None]=mapped_column(Float, nullable=True)
    activity_type: Mapped[str|None]=mapped_column(String(200), nullable=True)
    product_id: Mapped[int|None]=mapped_column(ForeignKey('products.id'), index=True)
    phone: Mapped[str|None]=mapped_column(String(80), nullable=True)
    website: Mapped[str|None]=mapped_column(Text, nullable=True)
    source_id: Mapped[int|None]=mapped_column(ForeignKey('sources.id'), nullable=True, index=True)
    source_url: Mapped[str|None]=mapped_column(Text, nullable=True)
    source_title: Mapped[str|None]=mapped_column(String(300), nullable=True)
    retrieved_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True), nullable=True)
    verification_status: Mapped[str]=mapped_column(String(30), default='Unverified', index=True)
    confidence: Mapped[float]=mapped_column(Float, default=0.0)
    is_archived: Mapped[bool]=mapped_column(Boolean, default=False, index=True)

class Demand(TimestampMixin, Base):
    __tablename__='demands'
    id: Mapped[int]=mapped_column(primary_key=True)
    product_id: Mapped[int]=mapped_column(ForeignKey('products.id'), index=True)
    raw_text: Mapped[str|None]=mapped_column(Text, nullable=True)
    quantity: Mapped[float|None]=mapped_column(Float, nullable=True)
    unit: Mapped[str|None]=mapped_column(String(30), nullable=True)
    country: Mapped[str]=mapped_column(String(100), index=True)
    city: Mapped[str|None]=mapped_column(String(120), nullable=True, index=True)
    latitude: Mapped[float|None]=mapped_column(Float, nullable=True)
    longitude: Mapped[float|None]=mapped_column(Float, nullable=True)
    urgency: Mapped[str|None]=mapped_column(String(80), nullable=True)
    source_id: Mapped[int|None]=mapped_column(ForeignKey('sources.id'), nullable=True, index=True)
    source_url: Mapped[str|None]=mapped_column(Text, nullable=True)
    published_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True), nullable=True)
    confidence: Mapped[float]=mapped_column(Float, default=0.0)
    verification_status: Mapped[str]=mapped_column(String(30), default='Unverified', index=True)
    verification_notes: Mapped[str|None]=mapped_column(Text, nullable=True)
    is_archived: Mapped[bool]=mapped_column(Boolean, default=False, index=True)

class SourceSignal(TimestampMixin, Base):
    __tablename__='source_signals'
    id: Mapped[int]=mapped_column(primary_key=True)
    source_id: Mapped[int|None]=mapped_column(ForeignKey('sources.id'), nullable=True, index=True)
    raw_text: Mapped[str]=mapped_column(Text)
    source_url: Mapped[str|None]=mapped_column(Text, nullable=True)
    source_title: Mapped[str|None]=mapped_column(String(300), nullable=True)
    retrieved_at: Mapped[datetime]=mapped_column(DateTime(timezone=True), default=now)
    published_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True), nullable=True)
    verification_status: Mapped[str]=mapped_column(String(30), default='Unverified', index=True)
    confidence: Mapped[float]=mapped_column(Float, default=0.0)
    normalized_payload: Mapped[dict]=mapped_column(JSON, default=dict)
    content_hash: Mapped[str|None]=mapped_column(String(64), nullable=True, index=True)
    external_key: Mapped[str|None]=mapped_column(String(500), nullable=True, index=True)
    freshness_status: Mapped[str]=mapped_column(String(30), default='Unknown', index=True)
    freshness_score: Mapped[float|None]=mapped_column(Float, nullable=True, index=True)
    observed_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True), nullable=True, index=True)
    updated_at_source: Mapped[datetime|None]=mapped_column(DateTime(timezone=True), nullable=True, index=True)
    expires_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True), nullable=True, index=True)
    last_verified_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True), nullable=True, index=True)

class Opportunity(TimestampMixin, Base):
    __tablename__='opportunities'
    id: Mapped[int]=mapped_column(primary_key=True)
    manufacturer_id: Mapped[int]=mapped_column(ForeignKey('manufacturers.id'), index=True)
    customer_id: Mapped[int]=mapped_column(ForeignKey('customers.id'), index=True)
    supplier_id: Mapped[int|None]=mapped_column(ForeignKey('suppliers.id'), nullable=True, index=True)
    buyer_id: Mapped[int|None]=mapped_column(ForeignKey('buyers.id'), nullable=True, index=True)
    demand_id: Mapped[int|None]=mapped_column(ForeignKey('demands.id'), nullable=True, index=True)
    product_id: Mapped[int]=mapped_column(ForeignKey('products.id'), index=True)
    market_id: Mapped[int|None]=mapped_column(ForeignKey('markets.id'), nullable=True, index=True)
    score: Mapped[float]=mapped_column(Float, index=True)
    product_fit: Mapped[float]=mapped_column(Float)
    capacity_score: Mapped[float|None]=mapped_column(Float, nullable=True)
    demand_score: Mapped[float]=mapped_column(Float)
    trust_score: Mapped[float|None]=mapped_column(Float, nullable=True)
    location_score: Mapped[float|None]=mapped_column(Float, nullable=True)
    price_score: Mapped[float|None]=mapped_column(Float, nullable=True)
    logistics_score: Mapped[float|None]=mapped_column(Float, nullable=True)
    evidence_score: Mapped[float|None]=mapped_column(Float, nullable=True)
    freshness_score: Mapped[float|None]=mapped_column(Float, nullable=True)
    buyer_reliability_score: Mapped[float|None]=mapped_column(Float, nullable=True)
    supplier_reliability_score: Mapped[float|None]=mapped_column(Float, nullable=True)
    score_breakdown: Mapped[dict]=mapped_column(JSON, default=dict)
    distance_km: Mapped[float|None]=mapped_column(Float, nullable=True)
    route: Mapped[dict]=mapped_column(JSON, default=dict)
    priority: Mapped[str]=mapped_column(String(20), index=True)
    verification_status: Mapped[str]=mapped_column(String(30), default='Unverified')
    next_action: Mapped[str]=mapped_column(Text)
    is_archived: Mapped[bool]=mapped_column(Boolean, default=False, index=True)
    opportunity_stage: Mapped[str]=mapped_column(String(40), default='Discovered', index=True)
    stage_due_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True), nullable=True, index=True)
    stage_owner_id: Mapped[int|None]=mapped_column(ForeignKey('admins.id'), nullable=True, index=True)
    stage_reason: Mapped[str|None]=mapped_column(Text, nullable=True)
    lost_reason: Mapped[str|None]=mapped_column(Text, nullable=True)
    closed_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True), nullable=True)
    stage_updated_at: Mapped[datetime]=mapped_column(DateTime(timezone=True), default=now, nullable=False, index=True)

class CommercialFact(TimestampMixin, Base):
    __tablename__='commercial_facts'
    id: Mapped[int]=mapped_column(primary_key=True)
    entity_type: Mapped[str]=mapped_column(String(60), index=True)
    entity_id: Mapped[int]=mapped_column(Integer, index=True)
    fact_type: Mapped[str]=mapped_column(String(100), index=True)
    value: Mapped[dict]=mapped_column(JSON, default=dict)
    source_signal_id: Mapped[int|None]=mapped_column(ForeignKey('source_signals.id'), nullable=True, index=True)
    evidence_id: Mapped[int|None]=mapped_column(ForeignKey('verification_evidence.id'), nullable=True, index=True)
    observed_at: Mapped[datetime]=mapped_column(DateTime(timezone=True), default=now, index=True)
    valid_until: Mapped[datetime|None]=mapped_column(DateTime(timezone=True), nullable=True, index=True)
    confidence: Mapped[float]=mapped_column(Float, default=0.0, index=True)
    status: Mapped[str]=mapped_column(String(30), default='Unverified', index=True)

class FXRate(TimestampMixin, Base):
    __tablename__='fx_rates'
    id: Mapped[int]=mapped_column(primary_key=True)
    base_currency: Mapped[str]=mapped_column(String(10), index=True)
    quote_currency: Mapped[str]=mapped_column(String(10), index=True)
    rate: Mapped[float]=mapped_column(Float)
    source_id: Mapped[int|None]=mapped_column(ForeignKey('sources.id'), nullable=True, index=True)
    source_url: Mapped[str|None]=mapped_column(Text, nullable=True)
    observed_at: Mapped[datetime]=mapped_column(DateTime(timezone=True), default=now, index=True)
    expires_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True), nullable=True, index=True)
    confidence: Mapped[float]=mapped_column(Float, default=0.0, index=True)
    status: Mapped[str]=mapped_column(String(30), default='Unverified', index=True)

class AIInference(TimestampMixin, Base):
    __tablename__='ai_inferences'
    id: Mapped[int]=mapped_column(primary_key=True)
    task_type: Mapped[str]=mapped_column(String(80), index=True)
    model: Mapped[str]=mapped_column(String(120))
    model_version: Mapped[str]=mapped_column(String(120))
    generated_at: Mapped[datetime]=mapped_column(DateTime(timezone=True), default=now, index=True)
    confidence: Mapped[float]=mapped_column(Float, default=0.0, index=True)
    evidence_ids: Mapped[list]=mapped_column(JSON, default=list)
    input_hash: Mapped[str|None]=mapped_column(String(64), nullable=True, index=True)
    output: Mapped[dict]=mapped_column(JSON, default=dict)

class SourceTrust(TimestampMixin, Base):
    __tablename__='source_trust'
    id: Mapped[int]=mapped_column(primary_key=True)
    source_id: Mapped[int]=mapped_column(ForeignKey('sources.id'), unique=True, index=True)
    base_score: Mapped[float]=mapped_column(Float, default=0.5)
    reliability_score: Mapped[float]=mapped_column(Float, default=0.5)
    freshness_score: Mapped[float]=mapped_column(Float, default=0.5)
    identity_score: Mapped[float]=mapped_column(Float, default=0.5)
    overall_score: Mapped[float]=mapped_column(Float, default=0.5, index=True)
    rationale: Mapped[dict]=mapped_column(JSON, default=dict)

class VerificationEvidence(TimestampMixin, Base):
    __tablename__='verification_evidence'
    id: Mapped[int]=mapped_column(primary_key=True)
    entity_type: Mapped[str]=mapped_column(String(60), index=True)
    entity_id: Mapped[int]=mapped_column(Integer, index=True)
    source_signal_id: Mapped[int|None]=mapped_column(ForeignKey('source_signals.id'), nullable=True, index=True)
    evidence_type: Mapped[str]=mapped_column(String(80), index=True)
    weight: Mapped[float]=mapped_column(Float, default=0.5)
    excerpt: Mapped[str|None]=mapped_column(Text, nullable=True)
    source_url: Mapped[str|None]=mapped_column(Text, nullable=True)
    details: Mapped[dict]=mapped_column(JSON, default=dict)

class DiscoveryCandidate(TimestampMixin, Base):
    __tablename__='discovery_candidates'
    id: Mapped[int]=mapped_column(primary_key=True)
    source_signal_id: Mapped[int|None]=mapped_column(ForeignKey('source_signals.id'), nullable=True, index=True)
    name: Mapped[str|None]=mapped_column(String(250), nullable=True, index=True)
    country: Mapped[str|None]=mapped_column(String(100), nullable=True, index=True)
    city: Mapped[str|None]=mapped_column(String(120), nullable=True, index=True)
    activity_type: Mapped[str|None]=mapped_column(String(200), nullable=True)
    product_name: Mapped[str|None]=mapped_column(String(200), nullable=True, index=True)
    candidate_type: Mapped[str]=mapped_column(String(50), default='Potential Customer', index=True)
    demand_likelihood: Mapped[float]=mapped_column(Float, default=0.0)
    confidence: Mapped[float]=mapped_column(Float, default=0.0)
    evidence: Mapped[dict]=mapped_column(JSON, default=dict)
    status: Mapped[str]=mapped_column(String(30), default='Review', index=True)
    source_url: Mapped[str|None]=mapped_column(Text, nullable=True)
    source_title: Mapped[str|None]=mapped_column(String(300), nullable=True)
    is_archived: Mapped[bool]=mapped_column(Boolean, default=False, index=True)
    canonical_key: Mapped[str|None]=mapped_column(String(300), nullable=True, index=True)
    duplicate_of_id: Mapped[int|None]=mapped_column(Integer, nullable=True, index=True)
    trust_score: Mapped[float]=mapped_column(Float, default=0.0, index=True)

class TransportProvider(TimestampMixin, Base):
    __tablename__='transport_providers'
    id: Mapped[int]=mapped_column(primary_key=True)
    name: Mapped[str]=mapped_column(String(250), index=True)
    country: Mapped[str]=mapped_column(String(100))
    contact: Mapped[str|None]=mapped_column(String(120), nullable=True)
    active: Mapped[bool]=mapped_column(Boolean, default=True)
    default_currency: Mapped[str]=mapped_column(String(10), default='USD')
    languages: Mapped[list]=mapped_column(JSON, default=list)
    incoterms: Mapped[list]=mapped_column(JSON, default=list)
    transport_modes: Mapped[list]=mapped_column(JSON, default=list)
    scoring_weights: Mapped[dict]=mapped_column(JSON, default=dict)
    commercial_rules: Mapped[dict]=mapped_column(JSON, default=dict)

class TransportRoute(TimestampMixin, Base):
    __tablename__='transport_routes'
    id: Mapped[int]=mapped_column(primary_key=True)
    origin: Mapped[str]=mapped_column(String(200), index=True)
    destination: Mapped[str]=mapped_column(String(200), index=True)
    provider_id: Mapped[int|None]=mapped_column(ForeignKey('transport_providers.id'), nullable=True)
    capacity: Mapped[float|None]=mapped_column(Float, nullable=True)
    capacity_unit: Mapped[str|None]=mapped_column(String(30), nullable=True)
    cost: Mapped[float|None]=mapped_column(Float, nullable=True)
    currency: Mapped[str|None]=mapped_column(String(10), nullable=True)
    eta_hours: Mapped[float|None]=mapped_column(Float, nullable=True)

class Verification(TimestampMixin, Base):
    __tablename__='verifications'
    id: Mapped[int]=mapped_column(primary_key=True)
    entity_type: Mapped[str]=mapped_column(String(50), index=True)
    entity_id: Mapped[int]=mapped_column(Integer, index=True)
    status: Mapped[str]=mapped_column(String(30), index=True)
    evidence: Mapped[dict]=mapped_column(JSON, default=dict)
    reviewer: Mapped[str|None]=mapped_column(String(100), nullable=True)

class AuditLog(TimestampMixin, Base):
    __tablename__='audit_logs'
    id: Mapped[int]=mapped_column(primary_key=True)
    admin_id: Mapped[int|None]=mapped_column(ForeignKey('admins.id'), nullable=True, index=True)
    action: Mapped[str]=mapped_column(String(120), index=True)
    entity_type: Mapped[str|None]=mapped_column(String(60), nullable=True)
    entity_id: Mapped[int|None]=mapped_column(Integer, nullable=True)
    details: Mapped[dict]=mapped_column(JSON, default=dict)

Index('ix_manufacturer_geo','manufacturers','latitude','longitude')
Index('ix_customer_geo','customers','latitude','longitude')

class OpportunityAction(TimestampMixin, Base):
    __tablename__='opportunity_actions'
    id: Mapped[int]=mapped_column(primary_key=True)
    opportunity_id: Mapped[int]=mapped_column(ForeignKey('opportunities.id'), index=True)
    action_type: Mapped[str]=mapped_column(String(40), index=True)
    status: Mapped[str]=mapped_column(String(30), default='Planned', index=True)
    subject: Mapped[str|None]=mapped_column(String(250), nullable=True)
    notes: Mapped[str|None]=mapped_column(Text, nullable=True)
    channel: Mapped[str|None]=mapped_column(String(40), nullable=True)
    due_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True), nullable=True, index=True)
    completed_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True), nullable=True)
    result: Mapped[str|None]=mapped_column(Text, nullable=True)
    created_by: Mapped[int|None]=mapped_column(ForeignKey('admins.id'), nullable=True, index=True)

class RFQDocument(TimestampMixin, Base):
    __tablename__='rfq_documents'
    id: Mapped[int]=mapped_column(primary_key=True)
    opportunity_id: Mapped[int]=mapped_column(ForeignKey('opportunities.id'), index=True)
    channel: Mapped[str]=mapped_column(String(30), default='whatsapp', index=True)
    language: Mapped[str]=mapped_column(String(10), default='en')
    title: Mapped[str]=mapped_column(String(250))
    body: Mapped[str]=mapped_column(Text)
    status: Mapped[str]=mapped_column(String(30), default='Draft', index=True)
    sent_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True), nullable=True)
    response_due_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True), nullable=True)
    metadata_json: Mapped[dict]=mapped_column('metadata', JSON, default=dict)
    created_by: Mapped[int|None]=mapped_column(ForeignKey('admins.id'), nullable=True, index=True)

class CommunicationLog(TimestampMixin, Base):
    __tablename__='communication_logs'
    id: Mapped[int]=mapped_column(primary_key=True)
    opportunity_id: Mapped[int]=mapped_column(ForeignKey('opportunities.id'), index=True)
    rfq_id: Mapped[int|None]=mapped_column(ForeignKey('rfq_documents.id'), nullable=True, index=True)
    channel: Mapped[str]=mapped_column(String(30), index=True)
    direction: Mapped[str]=mapped_column(String(20), default='outbound')
    status: Mapped[str]=mapped_column(String(30), default='Draft', index=True)
    recipient: Mapped[str|None]=mapped_column(String(250), nullable=True)
    subject: Mapped[str|None]=mapped_column(String(250), nullable=True)
    message: Mapped[str]=mapped_column(Text)
    sent_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True), nullable=True)
    response_summary: Mapped[str|None]=mapped_column(Text, nullable=True)
    created_by: Mapped[int|None]=mapped_column(ForeignKey('admins.id'), nullable=True, index=True)

class SupplierQuote(TimestampMixin, Base):
    __tablename__='supplier_quotes'
    id: Mapped[int]=mapped_column(primary_key=True)
    opportunity_id: Mapped[int]=mapped_column(ForeignKey('opportunities.id'), index=True)
    manufacturer_id: Mapped[int|None]=mapped_column(ForeignKey('manufacturers.id'), nullable=True, index=True)
    supplier_id: Mapped[int|None]=mapped_column(ForeignKey('suppliers.id'), nullable=True, index=True)
    supplier_name: Mapped[str]=mapped_column(String(250))
    currency: Mapped[str]=mapped_column(String(10), default='USD')
    unit_price: Mapped[float]=mapped_column(Float)
    quantity: Mapped[float]=mapped_column(Float)
    unit: Mapped[str]=mapped_column(String(30), default='kg')
    incoterm: Mapped[str]=mapped_column(String(20), default='EXW')
    freight_cost: Mapped[float]=mapped_column(Float, default=0.0)
    other_cost: Mapped[float]=mapped_column(Float, default=0.0)
    lead_time_days: Mapped[int|None]=mapped_column(Integer, nullable=True)
    validity_days: Mapped[int|None]=mapped_column(Integer, nullable=True)
    notes: Mapped[str|None]=mapped_column(Text, nullable=True)
    source_url: Mapped[str|None]=mapped_column(Text, nullable=True)
    status: Mapped[str]=mapped_column(String(30), default='Unverified', index=True)

class CommercialOffer(TimestampMixin, Base):
    __tablename__='commercial_offers'
    id: Mapped[int]=mapped_column(primary_key=True)
    opportunity_id: Mapped[int]=mapped_column(ForeignKey('opportunities.id'), index=True)
    supplier_quote_id: Mapped[int|None]=mapped_column(ForeignKey('supplier_quotes.id'), nullable=True, index=True)
    currency: Mapped[str]=mapped_column(String(10), default='USD')
    exchange_rate: Mapped[float]=mapped_column(Float, default=1.0)
    fx_rate_id: Mapped[int|None]=mapped_column(ForeignKey('fx_rates.id'), nullable=True, index=True)
    quantity: Mapped[float]=mapped_column(Float)
    unit: Mapped[str]=mapped_column(String(30), default='kg')
    supplier_unit_price: Mapped[float]=mapped_column(Float, default=0.0)
    packaging_cost: Mapped[float]=mapped_column(Float, default=0.0)
    inland_cost: Mapped[float]=mapped_column(Float, default=0.0)
    export_cost: Mapped[float]=mapped_column(Float, default=0.0)
    freight_cost: Mapped[float]=mapped_column(Float, default=0.0)
    insurance_cost: Mapped[float]=mapped_column(Float, default=0.0)
    customs_cost: Mapped[float]=mapped_column(Float, default=0.0)
    other_cost: Mapped[float]=mapped_column(Float, default=0.0)
    commission_percent: Mapped[float]=mapped_column(Float, default=0.0)
    commission_fixed: Mapped[float]=mapped_column(Float, default=0.0)
    target_margin_percent: Mapped[float]=mapped_column(Float, default=10.0)
    fob_total: Mapped[float]=mapped_column(Float, default=0.0)
    cif_total: Mapped[float]=mapped_column(Float, default=0.0)
    fob_unit_price: Mapped[float]=mapped_column(Float, default=0.0)
    cif_unit_price: Mapped[float]=mapped_column(Float, default=0.0)
    estimated_profit: Mapped[float]=mapped_column(Float, default=0.0)
    estimated_profit_percent: Mapped[float]=mapped_column(Float, default=0.0)
    logistics_scenario_id: Mapped[int|None]=mapped_column(ForeignKey('logistics_scenarios.id'), nullable=True, index=True)
    incoterm: Mapped[str]=mapped_column(String(20), default='CIF')
    cfr_total: Mapped[float]=mapped_column(Float, default=0.0)
    cfr_unit_price: Mapped[float]=mapped_column(Float, default=0.0)
    landed_total: Mapped[float]=mapped_column(Float, default=0.0)
    landed_unit_price: Mapped[float]=mapped_column(Float, default=0.0)
    status: Mapped[str]=mapped_column(String(30), default='Draft', index=True)
    notes: Mapped[str|None]=mapped_column(Text, nullable=True)
    assumptions: Mapped[dict]=mapped_column(JSON, default=dict)
    created_by: Mapped[int|None]=mapped_column(ForeignKey('admins.id'), nullable=True, index=True)

class LogisticsScenario(TimestampMixin, Base):
    __tablename__='logistics_scenarios'
    id: Mapped[int]=mapped_column(primary_key=True)
    opportunity_id: Mapped[int]=mapped_column(ForeignKey('opportunities.id'), index=True)
    name: Mapped[str]=mapped_column(String(200))
    origin: Mapped[str]=mapped_column(String(250))
    destination: Mapped[str]=mapped_column(String(250))
    transport_mode: Mapped[str]=mapped_column(String(40), default='road', index=True)
    border_or_port: Mapped[str|None]=mapped_column(String(160), nullable=True, index=True)
    distance_km: Mapped[float|None]=mapped_column(Float, nullable=True)
    transit_days: Mapped[float|None]=mapped_column(Float, nullable=True)
    freight_total: Mapped[float]=mapped_column(Float, default=0.0)
    currency: Mapped[str]=mapped_column(String(10), default='USD')
    insurance_percent: Mapped[float]=mapped_column(Float, default=0.0)
    insurance_fixed: Mapped[float]=mapped_column(Float, default=0.0)
    customs_total: Mapped[float]=mapped_column(Float, default=0.0)
    destination_handling: Mapped[float]=mapped_column(Float, default=0.0)
    other_cost: Mapped[float]=mapped_column(Float, default=0.0)
    capacity_value: Mapped[float|None]=mapped_column(Float, nullable=True)
    capacity_unit: Mapped[str|None]=mapped_column(String(30), nullable=True)
    source_url: Mapped[str|None]=mapped_column(Text, nullable=True)
    source_title: Mapped[str|None]=mapped_column(String(300), nullable=True)
    verification_status: Mapped[str]=mapped_column(String(30), default='Unverified', index=True)
    assumptions: Mapped[dict]=mapped_column(JSON, default=dict)
    is_active: Mapped[bool]=mapped_column(Boolean, default=True, index=True)

class MarketPriceObservation(TimestampMixin, Base):
    __tablename__='market_price_observations'
    id: Mapped[int]=mapped_column(primary_key=True)
    product_id: Mapped[int]=mapped_column(ForeignKey('products.id'), index=True)
    market: Mapped[str]=mapped_column(String(160), index=True)
    country: Mapped[str|None]=mapped_column(String(100), nullable=True, index=True)
    city: Mapped[str|None]=mapped_column(String(120), nullable=True, index=True)
    grade: Mapped[str|None]=mapped_column(String(120), nullable=True, index=True)
    specification: Mapped[dict]=mapped_column(JSON, default=dict)
    price: Mapped[float]=mapped_column(Float)
    currency: Mapped[str]=mapped_column(String(10), index=True)
    unit: Mapped[str]=mapped_column(String(30), index=True)
    incoterm: Mapped[str|None]=mapped_column(String(20), nullable=True, index=True)
    quantity: Mapped[float|None]=mapped_column(Float, nullable=True)
    source_id: Mapped[int|None]=mapped_column(ForeignKey('sources.id'), nullable=True, index=True)
    source_url: Mapped[str|None]=mapped_column(Text, nullable=True)
    source_title: Mapped[str|None]=mapped_column(String(300), nullable=True)
    observed_at: Mapped[datetime]=mapped_column(DateTime(timezone=True), default=now, index=True)
    verification_status: Mapped[str]=mapped_column(String(30), default='Unverified', index=True)
    confidence: Mapped[float]=mapped_column(Float, default=0.0)
    notes: Mapped[str|None]=mapped_column(Text, nullable=True)

class MarketPriceBenchmark(TimestampMixin, Base):
    __tablename__='market_price_benchmarks'
    id: Mapped[int]=mapped_column(primary_key=True)
    product_id: Mapped[int]=mapped_column(ForeignKey('products.id'), index=True)
    market: Mapped[str]=mapped_column(String(160), index=True)
    country: Mapped[str|None]=mapped_column(String(100), nullable=True, index=True)
    grade: Mapped[str|None]=mapped_column(String(120), nullable=True, index=True)
    unit: Mapped[str]=mapped_column(String(30), index=True)
    incoterm: Mapped[str|None]=mapped_column(String(20), nullable=True, index=True)
    currency: Mapped[str]=mapped_column(String(10))
    observation_count: Mapped[int]=mapped_column(Integer, default=0)
    effective_count: Mapped[int]=mapped_column(Integer, default=0)
    low_price: Mapped[float]=mapped_column(Float, default=0.0)
    p25_price: Mapped[float]=mapped_column(Float, default=0.0)
    median_price: Mapped[float]=mapped_column(Float, default=0.0)
    p75_price: Mapped[float]=mapped_column(Float, default=0.0)
    high_price: Mapped[float]=mapped_column(Float, default=0.0)
    weighted_median_price: Mapped[float]=mapped_column(Float, default=0.0)
    confidence: Mapped[float]=mapped_column(Float, default=0.0)
    dispersion_pct: Mapped[float]=mapped_column(Float, default=0.0)
    benchmark_status: Mapped[str]=mapped_column(String(30), default='Insufficient Data', index=True)
    as_of: Mapped[datetime]=mapped_column(DateTime(timezone=True), default=now, index=True)
    assumptions: Mapped[dict]=mapped_column(JSON, default=dict)

class Transaction(TimestampMixin, Base):
    __tablename__='transactions'
    id: Mapped[int]=mapped_column(primary_key=True)
    opportunity_id: Mapped[int]=mapped_column(ForeignKey('opportunities.id'), index=True)
    market_id: Mapped[int|None]=mapped_column(ForeignKey('markets.id'), nullable=True, index=True)
    commercial_offer_id: Mapped[int|None]=mapped_column(ForeignKey('commercial_offers.id'), nullable=True, index=True)
    customer_id: Mapped[int|None]=mapped_column(ForeignKey('customers.id'), nullable=True, index=True)
    manufacturer_id: Mapped[int|None]=mapped_column(ForeignKey('manufacturers.id'), nullable=True, index=True)
    product_id: Mapped[int]=mapped_column(ForeignKey('products.id'), index=True)
    status: Mapped[str]=mapped_column(String(40), default='Draft', index=True)
    currency: Mapped[str]=mapped_column(String(10), default='USD')
    quantity: Mapped[float]=mapped_column(Float)
    unit: Mapped[str]=mapped_column(String(30), default='kg')
    agreed_unit_price: Mapped[float|None]=mapped_column(Float, nullable=True)
    agreed_total: Mapped[float|None]=mapped_column(Float, nullable=True)
    incoterm: Mapped[str|None]=mapped_column(String(20), nullable=True)
    payment_status: Mapped[str]=mapped_column(String(30), default='Pending', index=True)
    logistics_status: Mapped[str]=mapped_column(String(30), default='Pending', index=True)
    confirmed_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True), nullable=True)
    paid_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True), nullable=True)
    shipped_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True), nullable=True)
    delivered_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True), nullable=True)
    completed_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True), nullable=True)
    actual_quantity: Mapped[float|None]=mapped_column(Float, nullable=True)
    actual_unit_price: Mapped[float|None]=mapped_column(Float, nullable=True)
    actual_total: Mapped[float|None]=mapped_column(Float, nullable=True)
    actual_freight: Mapped[float|None]=mapped_column(Float, nullable=True)
    actual_delivery_days: Mapped[float|None]=mapped_column(Float, nullable=True)
    outcome: Mapped[dict]=mapped_column(JSON, default=dict)
    notes: Mapped[str|None]=mapped_column(Text, nullable=True)
    created_by: Mapped[int|None]=mapped_column(ForeignKey('admins.id'), nullable=True, index=True)

class TransactionEvent(TimestampMixin, Base):
    __tablename__='transaction_events'
    id: Mapped[int]=mapped_column(primary_key=True)
    transaction_id: Mapped[int]=mapped_column(ForeignKey('transactions.id'), index=True)
    event_type: Mapped[str]=mapped_column(String(50), index=True)
    from_status: Mapped[str|None]=mapped_column(String(40), nullable=True)
    to_status: Mapped[str|None]=mapped_column(String(40), nullable=True)
    notes: Mapped[str|None]=mapped_column(Text, nullable=True)
    payload: Mapped[dict]=mapped_column(JSON, default=dict)
    created_by: Mapped[int|None]=mapped_column(ForeignKey('admins.id'), nullable=True, index=True)

class TradeOutcomeFeedback(TimestampMixin, Base):
    __tablename__='trade_outcome_feedback'
    id: Mapped[int]=mapped_column(primary_key=True)
    transaction_id: Mapped[int]=mapped_column(ForeignKey('transactions.id'), unique=True, index=True)
    opportunity_id: Mapped[int]=mapped_column(ForeignKey('opportunities.id'), index=True)
    product_id: Mapped[int]=mapped_column(ForeignKey('products.id'), index=True)
    customer_id: Mapped[int|None]=mapped_column(ForeignKey('customers.id'), nullable=True, index=True)
    manufacturer_id: Mapped[int|None]=mapped_column(ForeignKey('manufacturers.id'), nullable=True, index=True)
    success_score: Mapped[float|None]=mapped_column(Float, nullable=True)
    actual_price_delta_pct: Mapped[float|None]=mapped_column(Float, nullable=True)
    actual_freight_delta_pct: Mapped[float|None]=mapped_column(Float, nullable=True)
    delivery_days: Mapped[float|None]=mapped_column(Float, nullable=True)
    quantity_variance_pct: Mapped[float|None]=mapped_column(Float, nullable=True)
    feedback: Mapped[dict]=mapped_column(JSON, default=dict)
    observed_at: Mapped[datetime]=mapped_column(DateTime(timezone=True), default=now, index=True)
    created_by: Mapped[int|None]=mapped_column(ForeignKey('admins.id'), nullable=True, index=True)

class AlertEvent(TimestampMixin, Base):
    __tablename__='alert_events'
    id: Mapped[int]=mapped_column(primary_key=True)
    opportunity_id: Mapped[int]=mapped_column(ForeignKey('opportunities.id'), index=True)
    alert_type: Mapped[str]=mapped_column(String(80), index=True)
    severity: Mapped[str]=mapped_column(String(20), index=True)
    status: Mapped[str]=mapped_column(String(30), default='New', index=True)
    message: Mapped[str]=mapped_column(Text)
    reason: Mapped[str|None]=mapped_column(Text, nullable=True)
    dedup_key: Mapped[str]=mapped_column(String(64), index=True)
    payload: Mapped[dict]=mapped_column(JSON, default=dict)
    first_seen_at: Mapped[datetime]=mapped_column(DateTime(timezone=True), default=now, index=True)
    last_seen_at: Mapped[datetime]=mapped_column(DateTime(timezone=True), default=now, index=True)
    acknowledged_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True), nullable=True)
    resolved_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True), nullable=True)
    created_by: Mapped[int|None]=mapped_column(ForeignKey('admins.id'), nullable=True, index=True)

class LandedCostCalculation(TimestampMixin, Base):
    __tablename__='landed_cost_calculations'
    id: Mapped[int]=mapped_column(primary_key=True)
    opportunity_id: Mapped[int|None]=mapped_column(ForeignKey('opportunities.id'), nullable=True, index=True)
    commercial_offer_id: Mapped[int|None]=mapped_column(ForeignKey('commercial_offers.id'), nullable=True, index=True)
    logistics_scenario_id: Mapped[int|None]=mapped_column(ForeignKey('logistics_scenarios.id'), nullable=True, index=True)
    import_cost_rule_id: Mapped[int|None]=mapped_column(ForeignKey('import_cost_rules.id'), nullable=True, index=True)
    hs_code: Mapped[str|None]=mapped_column(String(30), nullable=True, index=True)
    currency: Mapped[str]=mapped_column(String(10), default='USD')
    quantity: Mapped[float]=mapped_column(Float, default=0.0)
    unit: Mapped[str]=mapped_column(String(30), default='kg')
    supplier_cost: Mapped[float]=mapped_column(Float, default=0.0)
    packaging_cost: Mapped[float]=mapped_column(Float, default=0.0)
    inland_cost: Mapped[float]=mapped_column(Float, default=0.0)
    export_cost: Mapped[float]=mapped_column(Float, default=0.0)
    freight_cost: Mapped[float]=mapped_column(Float, default=0.0)
    insurance_cost: Mapped[float]=mapped_column(Float, default=0.0)
    customs_value: Mapped[float]=mapped_column(Float, default=0.0)
    import_taxes_and_fees: Mapped[float]=mapped_column(Float, default=0.0)
    destination_handling: Mapped[float]=mapped_column(Float, default=0.0)
    other_cost: Mapped[float]=mapped_column(Float, default=0.0)
    total_landed_cost: Mapped[float]=mapped_column(Float, default=0.0)
    landed_unit_cost: Mapped[float]=mapped_column(Float, default=0.0)
    fx_rate: Mapped[float|None]=mapped_column(Float, nullable=True)
    status: Mapped[str]=mapped_column(String(30), default='Calculated', index=True)
    assumptions: Mapped[dict]=mapped_column(JSON, default=dict)

class TradeRouteProfile(TimestampMixin, Base):
    __tablename__='trade_route_profiles'
    id: Mapped[int]=mapped_column(primary_key=True)
    opportunity_id: Mapped[int|None]=mapped_column(ForeignKey('opportunities.id'), nullable=True, index=True)
    market_id: Mapped[int|None]=mapped_column(ForeignKey('markets.id'), nullable=True, index=True)
    name: Mapped[str]=mapped_column(String(200))
    origin: Mapped[str]=mapped_column(String(250))
    destination: Mapped[str]=mapped_column(String(250))
    currency: Mapped[str]=mapped_column(String(10), default='USD')
    verification_status: Mapped[str]=mapped_column(String(30), default='Unverified', index=True)
    source_url: Mapped[str|None]=mapped_column(Text, nullable=True)
    source_title: Mapped[str|None]=mapped_column(String(300), nullable=True)
    assumptions: Mapped[dict]=mapped_column(JSON, default=dict)
    is_active: Mapped[bool]=mapped_column(Boolean, default=True, index=True)

class TradeRouteSegment(TimestampMixin, Base):
    __tablename__='trade_route_segments'
    id: Mapped[int]=mapped_column(primary_key=True)
    route_id: Mapped[int]=mapped_column(ForeignKey('trade_route_profiles.id'), index=True)
    sequence: Mapped[int]=mapped_column(Integer, default=1, index=True)
    segment_type: Mapped[str]=mapped_column(String(30), default='transport', index=True)
    from_location: Mapped[str]=mapped_column(String(250))
    to_location: Mapped[str]=mapped_column(String(250))
    transport_mode: Mapped[str]=mapped_column(String(40), default='road')
    border_or_port: Mapped[str|None]=mapped_column(String(160), nullable=True)
    distance_km: Mapped[float|None]=mapped_column(Float, nullable=True)
    transit_days: Mapped[float|None]=mapped_column(Float, nullable=True)
    freight_cost: Mapped[float]=mapped_column(Float, default=0.0)
    border_cost: Mapped[float]=mapped_column(Float, default=0.0)
    transit_cost: Mapped[float]=mapped_column(Float, default=0.0)
    destination_handling: Mapped[float]=mapped_column(Float, default=0.0)
    other_cost: Mapped[float]=mapped_column(Float, default=0.0)
    currency: Mapped[str]=mapped_column(String(10), default='USD')
    verification_status: Mapped[str]=mapped_column(String(30), default='Unverified', index=True)
    source_url: Mapped[str|None]=mapped_column(Text, nullable=True)
    assumptions: Mapped[dict]=mapped_column(JSON, default=dict)

class TradeRouteCalculation(TimestampMixin, Base):
    __tablename__='trade_route_calculations'
    id: Mapped[int]=mapped_column(primary_key=True)
    route_id: Mapped[int]=mapped_column(ForeignKey('trade_route_profiles.id'), index=True)
    opportunity_id: Mapped[int|None]=mapped_column(ForeignKey('opportunities.id'), nullable=True, index=True)
    quantity: Mapped[float]=mapped_column(Float)
    currency: Mapped[str]=mapped_column(String(10))
    freight_total: Mapped[float]=mapped_column(Float, default=0.0)
    border_total: Mapped[float]=mapped_column(Float, default=0.0)
    transit_total: Mapped[float]=mapped_column(Float, default=0.0)
    destination_handling: Mapped[float]=mapped_column(Float, default=0.0)
    other_cost: Mapped[float]=mapped_column(Float, default=0.0)
    total_route_cost: Mapped[float]=mapped_column(Float, default=0.0)
    route_unit_cost: Mapped[float]=mapped_column(Float, default=0.0)
    distance_km: Mapped[float]=mapped_column(Float, default=0.0)
    transit_days: Mapped[float]=mapped_column(Float, default=0.0)
    status: Mapped[str]=mapped_column(String(30), default='Calculated', index=True)
    assumptions: Mapped[dict]=mapped_column(JSON, default=dict)

class TradeOptimizationRun(TimestampMixin, Base):
    __tablename__='trade_optimization_runs'
    id: Mapped[int]=mapped_column(primary_key=True)
    opportunity_id: Mapped[int]=mapped_column(ForeignKey('opportunities.id'), index=True)
    quantity: Mapped[float]=mapped_column(Float)
    target_currency: Mapped[str]=mapped_column(String(10), default='USD')
    status: Mapped[str]=mapped_column(String(30), default='Calculated', index=True)
    scenario_count: Mapped[int]=mapped_column(Integer, default=0)
    assumptions: Mapped[dict]=mapped_column(JSON, default=dict)
    created_by: Mapped[int|None]=mapped_column(ForeignKey('admins.id'), nullable=True, index=True)

class TradeOptimizationResult(TimestampMixin, Base):
    __tablename__='trade_optimization_results'
    id: Mapped[int]=mapped_column(primary_key=True)
    run_id: Mapped[int]=mapped_column(ForeignKey('trade_optimization_runs.id'), index=True)
    opportunity_id: Mapped[int]=mapped_column(ForeignKey('opportunities.id'), index=True)
    supplier_quote_id: Mapped[int]=mapped_column(ForeignKey('supplier_quotes.id'), index=True)
    route_id: Mapped[int]=mapped_column(ForeignKey('trade_route_profiles.id'), index=True)
    target_currency: Mapped[str]=mapped_column(String(10), default='USD')
    quantity: Mapped[float]=mapped_column(Float)
    supplier_goods_total: Mapped[float]=mapped_column(Float, default=0.0)
    supplier_other_cost: Mapped[float]=mapped_column(Float, default=0.0)
    route_cost: Mapped[float]=mapped_column(Float, default=0.0)
    import_taxes_and_fees: Mapped[float]=mapped_column(Float, default=0.0)
    total_trade_cost: Mapped[float]=mapped_column(Float, default=0.0)
    trade_unit_cost: Mapped[float]=mapped_column(Float, default=0.0)
    route_distance_km: Mapped[float]=mapped_column(Float, default=0.0)
    route_transit_days: Mapped[float]=mapped_column(Float, default=0.0)
    rank: Mapped[int]=mapped_column(Integer, default=0, index=True)
    assumptions: Mapped[dict]=mapped_column(JSON, default=dict)

class EntityIdentity(TimestampMixin, Base):
    __tablename__='entity_identities'
    id: Mapped[int]=mapped_column(primary_key=True)
    entity_type: Mapped[str]=mapped_column(String(30), index=True)
    entity_id: Mapped[int]=mapped_column(Integer, index=True)
    identity_type: Mapped[str]=mapped_column(String(30), index=True)
    normalized_value: Mapped[str]=mapped_column(String(500), index=True)
    source_id: Mapped[int|None]=mapped_column(ForeignKey('sources.id'), nullable=True, index=True)
    evidence: Mapped[dict]=mapped_column(JSON, default=dict)
    confidence: Mapped[float]=mapped_column(Float, default=0.0)

class EntityLink(TimestampMixin, Base):
    __tablename__='entity_links'
    id: Mapped[int]=mapped_column(primary_key=True)
    left_type: Mapped[str]=mapped_column(String(30), index=True)
    left_id: Mapped[int]=mapped_column(Integer, index=True)
    right_type: Mapped[str]=mapped_column(String(30), index=True)
    right_id: Mapped[int]=mapped_column(Integer, index=True)
    relation: Mapped[str]=mapped_column(String(30), default='possible_match', index=True)
    score: Mapped[float]=mapped_column(Float, default=0.0)
    reasons: Mapped[list]=mapped_column(JSON, default=list)
    evidence: Mapped[dict]=mapped_column(JSON, default=dict)
    reviewed: Mapped[bool]=mapped_column(Boolean, default=False, index=True)
    __table_args__=(Index('ix_entity_links_pair','left_type','left_id','right_type','right_id',unique=True),)

class SearchCache(TimestampMixin, Base):
    __tablename__='search_cache'
    id: Mapped[int]=mapped_column(primary_key=True)
    cache_key: Mapped[str]=mapped_column(String(64),unique=True,index=True)
    source: Mapped[str]=mapped_column(String(80),index=True)
    query: Mapped[str]=mapped_column(Text)
    parameters: Mapped[dict]=mapped_column(JSON,default=dict)
    payload: Mapped[dict]=mapped_column(JSON,default=dict)
    expires_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),index=True)
    hit_count: Mapped[int]=mapped_column(Integer,default=0)
    last_hit_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True)

class DiscoveryUsage(TimestampMixin, Base):
    __tablename__='discovery_usage'
    id: Mapped[int]=mapped_column(primary_key=True)
    scope_type: Mapped[str]=mapped_column(String(30), index=True)
    scope_key: Mapped[str]=mapped_column(String(200), index=True)
    window_started_at: Mapped[datetime]=mapped_column(DateTime(timezone=True), index=True)
    request_limit: Mapped[int]=mapped_column(Integer)
    requests_used: Mapped[int]=mapped_column(Integer, default=0)
    __table_args__=(Index('ux_discovery_usage_window','scope_type','scope_key','window_started_at',unique=True),)


class DiscoveryJob(TimestampMixin, Base):
    __tablename__='discovery_jobs'
    id: Mapped[int]=mapped_column(primary_key=True)
    job_type: Mapped[str]=mapped_column(String(50),index=True)
    status: Mapped[str]=mapped_column(String(30),default='queued',index=True)
    payload: Mapped[dict]=mapped_column(JSON,default=dict)
    result: Mapped[dict]=mapped_column(JSON,default=dict)
    error: Mapped[str|None]=mapped_column(Text,nullable=True)
    request_budget: Mapped[int]=mapped_column(Integer,default=50)
    requests_used: Mapped[int]=mapped_column(Integer,default=0)
    max_retries: Mapped[int]=mapped_column(Integer,default=3)
    retry_count: Mapped[int]=mapped_column(Integer,default=0)
    created_by: Mapped[int|None]=mapped_column(ForeignKey('admins.id'),nullable=True,index=True)
    started_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True)
    heartbeat_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True)
    lease_token: Mapped[str|None]=mapped_column(String(64),nullable=True,index=True)
    finished_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True)
